"""AI text detection — uses LLM to analyze writing patterns."""

import json
import logging

from openai import AsyncOpenAI

from app.config import settings
from app.models.schemas import AITextResult

logger = logging.getLogger(__name__)

_SYSTEM_PROMPT = """\
You are an expert AI-generated text analyst. Analyze the provided text and determine \
the probability that it was generated by an AI language model versus written by a human.

Evaluate these signals:
1. Perplexity patterns — does the text have uniformly low perplexity?
2. Vocabulary diversity — is the type-token ratio unusually uniform?
3. Sentence structure — are sentence lengths and structures too consistent?
4. Burstiness — does the text lack natural variation in complexity?
5. Stylistic markers — does it use common AI phrases or avoid colloquialisms?
6. Hedging patterns — excessive use of qualifiers like "it's important to note"

Return ONLY valid JSON with this exact structure (no markdown):
{
    "ai_probability": <float 0-1>,
    "confidence": "HIGH" | "MEDIUM" | "LOW",
    "signals": [
        {"name": "<signal name>", "weight": <float 0-1>}
    ],
    "verdict": "Likely AI-Generated" | "Possibly AI-Generated" | "Likely Human-Written"
}
"""


async def detect_ai_text(text: str) -> AITextResult:
    """Analyze text for AI generation probability using an LLM."""
    client = AsyncOpenAI(
        base_url=settings.llm_base_url,
        api_key=settings.llm_api_key,
    )

    # Truncate very long texts to avoid token limits
    truncated = text[:8000] if len(text) > 8000 else text

    response = await client.chat.completions.create(
        model=settings.llm_model_fast,
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": f"Analyze this text:\n\n{truncated}"},
        ],
        temperature=0.1,
        response_format={"type": "json_object"},
    )

    raw = response.choices[0].message.content or "{}"

    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        logger.error("LLM returned invalid JSON for AI text detection: %s", raw)
        return AITextResult(
            ai_probability=0.5,
            confidence="LOW",
            signals=[],
            verdict="Analysis Failed",
        )

    return AITextResult(
        ai_probability=data.get("ai_probability", 0.5),
        confidence=data.get("confidence", "LOW"),
        signals=data.get("signals", []),
        verdict=data.get("verdict", "Unknown"),
    )
